name: remove-pr

on:
  pull_request:
    types: [closed]
jobs:
  remove-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Prune PR files
        PR_PATH: "refs/pull/${ github.event.pull_request.number }/merge/"
        run: |
          rm -rf ${{ PR_PATH }}
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git commit -m "Prune ${ PR_PATH }"
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
