name: remove-pr

on:
  pull_request:
    types: [closed]

jobs:
  remove-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Prune PR files
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          echo "github: ${{ github }}"
          rm -rf "refs/pull/${{ github.event.pull_request.number }}/merge/"
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git commit -m "Prune refs/pull/${{ github.event.pull_request.number }}/merge/"
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
