name: remove-pr-from-wiki

on:
  pull_request:
    types: [closed]
jobs:
  trigger-pr-release:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
    run: |
      bash .github/remove-from-wiki.sh ${{ github.ref }}
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      WIKI_COMMIT_MESSAGE: "Remove build files for PR ${{ github.ref }}"
